[package]
authors = ["Zhao Guangjian<zgj0315@gmail.com>"]
description = "Some functions about CPE and CVE"
edition = "2021"
keywords = ["nvd", "cve", "cpe", "match", "cpe23uri"]
license-file = "LICENSE"
name = "nvd"
readme = "README.md"
repository = "https://github.com/zgj0315/nvd/"
version = "0.1.0"

[dependencies]
log = "0.4"

[dev-dependencies]
chrono = "0.4"
criterion = {version = "0.4", features = ["html_reports"]}
tracing = "0.1"
tracing-subscriber = "0.3"

[[bench]]
harness = false
name = "cpe_match_benchmark"
